# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - master

pool:
  vmImage: "windows-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "Use net6.0"
    inputs:
      packageType: "sdk"
      version: "6.0.x"

  - task: DotNetCoreCLI@2
    displayName: Restore nuget packages
    inputs:
      command: restore
      projects: "**/*.csproj"
      workingDirectory: $(Build.SourcesDirectory)

  - task: DotNetCoreCLI@2
    displayName: "Assemble Purchasing.Mvc"
    inputs:
      command: "publish"
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
      projects: "./Purchasing.Mvc/Purchasing.Mvc.csproj"
      arguments: "--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/Purchasing.Mvc"

  - task: DotNetCoreCLI@2
    displayName: "Assemble Purchasing Jobs"
    inputs:
      command: "publish"
      publishWebProjects: false
      zipAfterPublish: false
      modifyOutputPath: false
      projects: "**/Purchasing.Jobs.!(*Common)/*.csproj"
      arguments: "--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/Purchasing.Jobs"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
